name: Build
permissions:
  contents: write
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-x86_64-linux
          - os: macos-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-x86_64-apple-darwin
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}.exe
            asset_name: ${{ github.event.repository.name }}-x86_64-windows.exe
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: stable
        cache-dependency-path: go.mod
    - uses: actions/checkout@v4
    - name: Build
      run: go build -trimpath
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        overwrite: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: r${{ github.run_number }}
